version: "3.0"
services:
  indiserver:
    build:
      context: .
      args:
        INDIPY_BRANCH: master
    ports:
      - 7624:7624
    command:
      - indi_simulator_ccd
      - indi_simulator_focus
      - /app/tty.py
