name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Cache python packages
      uses: actions/cache@v2
      env:
        cache-name: test-python-packages
      with:
        path: '~/.local/**/site-packages'
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('requirements/**/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/tests.txt --user
        pip install black==22.1.0

    - name: Check with black
      run: |
        python -m black --check indi

    - name: Test with pytest
      run: |
        python -m pytest tests
